### ISSUE TITLE
运行后端历史记录报错

### ISSUE THREAD

**Issue by fl1906** [bravekingzhang/gpt-frontend-code-gen#2]
![image](https://github.com/bravekingzhang/gpt-frontend-code-gen/assets/73702449/6c26bcc4-e16e-4009-9a47-b8fe9251c0d2)

**Comment by bravekingzhang** [comment]
` git --version` 看看版本号

**Comment by bravekingzhang** [comment]
直接使用 docker 方式启动把，估计是你本地 git 的版本比较低

`docker-compose up -d --build`

**Comment by fl1906** [comment]
![image](https://github.com/bravekingzhang/gpt-frontend-code-gen/assets/73702449/e390799a-f7b8-43bb-aff0-f2b0950fa99c)
这是我的git版本号 我是win上启动的 docker 不太方便

**Comment by bravekingzhang** [comment]
我看我的版本是，2.39.3，尝试更新下。另外，Windows 上 docker 应该也是ok 的，这是一个多平台的呢

https://www.runoob.com/docker/windows-docker-install.html
