### ISSUE TITLE
docker-compose 部署后，generate-code 接口报错

### ISSUE THREAD

**Issue by dddreams** [bravekingzhang/gpt-frontend-code-gen#3]
![image](https://github.com/bravekingzhang/gpt-frontend-code-gen/assets/10234736/88798952-359a-4098-819f-b7d289152349)

git 命令找不到，不知道要用 git 干什么？

**Comment by bravekingzhang** [comment]
是为了跟踪变更记录，可以回到任意的历史记录。可以拉下最新代码，然后

`docker-compose up -d --build`
