### ISSUE TITLE
什么时候会出一版VUE的Ai生成

### ISSUE THREAD

**Issue by Ninshar** [bravekingzhang/gpt-frontend-code-gen#4]

**Comment by bravekingzhang** [comment]
可以自己定制一下，一些 Vue 的前端包，启动，复用后端就 ok&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月5日(周五) 下午4:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bravekingzhang/gpt-frontend-code-gen] 什么时候会出一版VUE的Ai生成 (Issue #4)
